server:
  port: 8800

spring:
  application:
    name: notification-service
  datasource:
    url: "jdbc:mysql://localhost:3306/notification_service"
    username: root
    password: Nokidding123456

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/