server:
  port: 8386

spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:mysql://localhost:3306/user_service"
    username: root
    password: Nokidding123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  security:
    enabled=false: