server:
  port: 8880
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
        - id: USER-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



#spring.application.name=api-gateway
#
#server.port=8880
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.routes[0].id=user-service
#spring.cloud.gateway.routes[0].uri=lb://user-service
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/user/**
