server:
  port: 8021

spring:
  application:
    name: cloudinary-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

cloudinary:
  cloud_name: dixauf66m
  api_key: 877693583549459
  api_secret: eUe-vaOov-6XXL0371bfrjfUwK4