server:
  port: 8089

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/order_service"
    username: root
    password: Nokidding123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ORDER-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/