server:
  port: 8087

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/payment_service"
    username: root
    password: Nokidding123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: PAYMENT-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/